### ISSUE TITLE
Research Center

### ISSUE THREAD

**Issue by TechStack** [TechStack/TS-RTS#41]

**Comment by Czarified** [comment]
In order to train certain types of units, research will need to be completed. Research costs a large amount of resources up front (including gold), and takes a long time to complete. Research is conducted in the Research Center (aka Academy). Once research has been completed once, it does not need to be completed again.

**Comment by Czarified** [comment]
This may be the same thing as issue #36. We might want to consolidate them together.

**Comment by Czarified** [comment]
Commit 3be2c90 added textures.
