### ISSUE TITLE
Unit Pathfinding Around Target Blocks

### ISSUE THREAD

**Issue by Czarified** [TechStack/TS-RTS#54]
Units cannot pathfind around target blocks very well, and get stuck easily.

**Comment by TechStack** [comment]
seeing same behavior with shulker boxes.
Minecraft AI ignores entities in its path finding.
Possible options:
- change the placement of the Target entities to be in a non pathable location instead of sticking out of the building (under another block for example)
- we could place a block at the same location as the Target block to force the AI to "See' the location as not traverse-able. May require a custom block with custom properties to avoid suffocation on the target entity. or may need to make the Target entity not able to suffocate

**Comment by Czarified** [comment]
Changing some of the target locations may help with this. As discussed on stream, targets should probably be equally distributed, over symmetrically distributed.

It won't help in situations like the town hall, where there are multiple places the units are defending and can easily get stuck.

**Comment by TechStack** [comment]
I did a test and if i were to place a cobble wall block inside the target they did not take damage .. it will need to be a specialized block that is smaller than the Target and is not a full block so they do not suffocate.
The block could represent a "Dead" target .. lets make it easy on ourselves and make it non team specific.

**Comment by Czarified** [comment]
That solves it, doesn't it? I'll just put cobble walls on every structure, and void blocks for the damaged versions.

**Comment by TechStack** [comment]
We need a different block the cobble walls can be seen thru the target block.

**Comment by Czarified** [comment]
Maybe a barrier block or single glass pane? I'll try to test some tonight, unless you beat me to it. You've been really knocking it out recently! ;)

**Comment by Czarified** [comment]
Structures updated to provide very few valid paths for units. This is currently the best available solution. Closing for now.
